### ISSUE TITLE
Concurrency problem in Hash.java

### ISSUE THREAD

**Issue by f24-astonkus** [joshjdevl/kalium-jni#18]
Hi there,

Just wanted to let you know about one problem we discovered: the Hash class is not thread-safe due to use of "private static byte[] buffer;".
When calculating hashes in multiple threads, they start overwriting each other's buffers.

Actually, there is no need for buffer to be static.

**Comment by joshjdevl** [comment]
Closing per [commit](https://github.com/joshjdevl/kalium-jni/commit/dff2d971e9303bd115831db018ea863de0ae4a8f)
